---
tags:
  - CreationTimeFormatted
  - DateCreated
  - DateTimeOriginal
  - GPSAltitude
  - GPSAreaInformation
  - GPSDateTime
  - GPSDOP
  - GPSLatitude
  - GPSLongitude
  - GPSProcessingMethod
  - ImageDescription
  - ImageHeight
  - ImageWidth
  - LensModel
  - MetadataDate
  - Make
  - Model
  - Orientation
  - PhotoTakenTimeFormatted
  - PhotoTakenTimeTimestamp
  - Software
  - State
  - City
  - Country
  - TimeStamp
  - YCbCrSubSampling
extensions:
  # Images
  - 3FR
  # - ARI (not exif?)
  - ARW
  - AVIF
  # - CAP (not exif?)
  # - CIN (not exif?)
  - CR2
  - CR3
  - CRW
  - DCR
  - DNG
  - ERF
  - FFF
  - GIF
  - HEIC
  - HEIF
  - IIQ
  - INSP
  - JPEG
  - JPG
  - JXL
  - K25
  - KDC
  - MRW
  - NEF
  - ORF
  - ORI
  - PEF
  - PNG
  - RAF
  - RAW
  - RWL
  - SR2
  - SRF
  - SRW
  - TIF
  - TIFF
  - WEBP
  - X3F
  # Videos
  - 3GP
  - AVI
  - FLV
  - INSV
  - M2TS
  - MKV
  - MOV
  - MP4
  - MPG
  - MTS
  - WEBM
  - WMV
tz_map:
  AUSTRALIA/WESTERN AUSTRALIA: Australia/West
  AUSTRALIA/QUEENSLAND: Australia/Queensland
  AUSTRALIA/NEW SOUTH WALES: Australia/NSW
  SINGAPORE: Singapore
  NEW ZEALAND/WELLINGTON: NZ
tag_priority:
  0:
    # Image Height
    - XMP:ImageHeight
    - EXIF:ImageHeight
    - RIFF:ImageHeight
    - QuickTime:ImageHeight
    - PNG:ImageHeight
    - MPEG:ImageHeight
    - Matroska:ImageHeight
    - H264:ImageHeight
    - GIF:ImageHeight
    - ASF:ImageHeight
    - Flash:ImageHeight
    # Image Width
    - XMP:ImageWidth
    - EXIF:ImageWidth
    - RIFF:ImageWidth
    - QuickTime:ImageWidth
    - PNG:ImageWidth
    - MPEG:ImageWidth
    - Matroska:ImageWidth
    - H264:ImageWidth
    - GIF:ImageWidth
    - ASF:ImageWidth
    - Flash:ImageWidth
    # Make / Model
    - XMP:Make
    - XMP:Model
  1:
    # Image Height
    - EXIF:ExifImageHeight
    # Image Width
    - EXIF:ExifImageWidth
    # Make / Model
    - EXIF:Make
    - EXIF:Model
  2:
    # Image Height
    - File:ImageHeight
    # Image Width
    - File:ImageWidth